name: Docker CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  ci-cd:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Login Docker Hub (CD)
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Build image (CI)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # 4️⃣ Test container (CI)
      - name: Run tests
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # 5️⃣ Push image (CD)
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

