name: Deploy Docker Compose on Server

on:
  push:
    branches:
      - main  # Branche de production

jobs:
  deploy:
    runs-on: [self-hosted, linux, docker]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          # Aller dans le dossier du projet (peut être le root si checkout l'a fait là)
          echo "-----Test container--------------"
          echo "Utilisateur courant : "
          id
          echo "Repertoire courant : "
          pwd
          ls
          echo "fin!!"
